# Generated by Django 4.2.2 on 2023-09-29 03:39

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='0000', editable=False, max_length=22, unique=True),
        ),
    ]
